### PR TITLE
add a check for data sources

### PR DESCRIPTION
**Pull request by beliaev-maksim**
based on the CI fail:
https://github.com/canonical/grafana-k8s-operator/runs/8205066126?check_suite_focus=true

raise more explicit exception

### CODE REVIEW

**Comment by rbarry82** [comment]
Let's put this into the PR in the comment. Spreading it across and linking to CI runs from other PRs hard to track back and forth

**Comment by beliaev-maksim** [comment]
hmm, PRs are completely unrelated, except for the error message

and this PR will not fix a pipeline issue. It will be just a more explicit error, while the real root cause why datasource is empty is unclear

**Comment by rbarry82** [comment]
> hmm, PRs are completely unrelated, except for the error message
> 
> and this PR will not fix a pipeline issue. It will be just a more explicit error, while the real root cause why datasource is empty is unclear

I can dig into the datasource issue, which may somehow be timing related with sqlite replication.

I meant that, in general, it's cleaner/easier for reviews and general process to have them all in one PR. In particular:

> based on the CI fail:
> https://github.com/canonical/grafana-k8s-operator/runs/8205066126?check_suite_focus=true

Is hard for reviewers. It's not from this PR, the run may be cleaned up at some point and can no longer be referenced, fixing it in a different PR wouldn't actually turn CI in the other green unless it was rebased after a merge, etc.

Can we merge these together?

**Comment by beliaev-maksim** [comment]
@rbarry82 
my motivation was that each PR should be as small as possible and at the same time self consistent and represent a complete feature/bug fix.
logically, these two PRs are not related. One is about version bumping and another is about error msges

but I can glue them together

**Comment by beliaev-maksim** [comment]
@rbarry82 
#119 was closed due to CI consolidation. That is actually an example why I split features in different PRs.

then I keep current PR opened

**Comment by rbarry82** [comment]
> @rbarry82 #119 was closed due to CI consolidation. That is actually an example why I split features in different PRs.
> 
> then I keep current PR opened

Kind of the point is that the PRs _are_ logically related and are not self-consistent if one of them cannot pass CI without a change in a different PR.

**Comment by beliaev-maksim** [comment]
@rbarry82 
I see what you mean

but unfortunately none of proposed by me PRs does not fix the pipeline, deeper investigation is required since now CI is failing even on `main`

current PR (#120) addresses just messaging for the future but does not fix the root cause

**Review by simskij — APPROVED** [review]

**Pull request merged**
