### PR TITLE
use pyright instead of mypy

### PR DESCRIPTION
**Pull request by lucabello**

### CODE REVIEW

**Review by PietroPasotti — APPROVED** [review]

**Review by PietroPasotti — CHANGES_REQUESTED** [review]
there seem to be some failing itests. patching kubernetes_service isn't going well. Maybe some Path issues?

**Comment by lucabello** [comment]
Fixed it!

**Review by sed-i — APPROVED** [review]

**Review by PietroPasotti — APPROVED** [review]
we're #ignoring and #Any'ing a bit too much for my taste, but fixing that (here) would be out of scope.

**Comment by lucabello** [comment]
Indeed; though all the custom-event-stuff has to be ignored unfortunately because there's no typing before runtime; a solution would be to write the type structures separately just for the linter, but that indeed falls out of the scope of this :)

At least know the fact that something's potentially fishy is explicit though!

**Pull request merged**
