### PR TITLE
Restart grafana after updating dashboards

### LINKED ISSUE #303: Grafana-k8s not rendering new dashboard from grafana-agent-k8s when the relation in between stays joined
We have a charm (tempest-k8s built on top of this [patch](https://review.opendev.org/c/openstack/sunbeam-charms/+/908205)) providing dashboard through `granfa-agent-k8s` to `grafana-k8s`. If we keep the relations between `grafana-agent-k8s` and `grafana-k8s` intact but deploy a new charm and relate it to grafana-agent-k8s:
```
$ juju deploy [charm]
$ juju relate [charm]:grafana-dashboard  grafana-agent-k8s:grafana-dashboards-consumer
```
we will not see the the dashboard showing on Grafana WebUI.

We can confirm that the dashboard file did land in grafana container and can be found by running the following command:
```
$ kubectl exec -n observability grafana-0 -it -c grafana -- /bin/bash -c "grep 'Tempest' /etc/grafana/provisioning/dashboards/*"
```

Manually deleting grafana-k8s pod or remove + rejoin the relation between grafana-k8s and grafana-agent-k8s solves the issue.

### PR DESCRIPTION
**Pull request by samuelallan72**
This ensures that dashboard changes are picked up by grafana.

Fixes #303

### CODE REVIEW

**Comment by chanchiwai-ray** [comment]
Did not apply this patch directly, but I tried `/charm/bin/pebble restart grafana` will force refresh the dashboard.

**Comment by mmkay** [comment]
Hi @samuelallan72, thank you for your contribution! There seems to be a reload API that might update the dashboards without going through the whole Grafana restart: https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-provisioning-configurations 

Could you have a look if that doesn't fix your issue in a better way?

**Comment by mmkay** [comment]
> Hi @mmkay , could you take another look at this? Thanks :)

Hey @samuelallan72 - I've rebased the branch to newest main and integration tests seem to be failing in the PR. At first sight it looks like there might be errors around the restart timing so this might require a deeper look. We have the issue in our team's minds so will likely get back to it in near future.

**Comment by samuelallan72** [comment]
Closing because this appears to have been fixed elsewhere. :)  See https://github.com/canonical/grafana-k8s-operator/issues/303

**Pull request closed without merging**
