### PR TITLE
Fix non-existing `errors` argument in GrafanaDashboardEvent

### PR DESCRIPTION
**Pull request by rbarry82**

### CODE REVIEW

**Comment by mmanciop** [comment]
@davigar15 I do not understand the rationale of this PR. Care to comment why this change is needed?

**Review by sed-i — APPROVED** [review]

**Comment by rbarry82** [comment]
> @davigar15 I do not understand the rationale of this PR. Care to comment why this change is needed?

Sorted on MM -- it's docs alignment.

**Comment by rbarry82** [comment]
@davigar15 edits from maintainers aren't allowed here. Can you run `black --line-length=99 lib/` and re-push?

**Comment by rbarry82** [comment]
@davigar15 ping?

**Comment by simskij** [comment]
Pinged @davigar15 on MM.

**Comment by davigar15** [comment]
Sorry for the late reply. In this line (https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L900) a kwargs `errors` is passed to the GrafanaDashboardEvent.

However, the constructor of GrafanaDashboardEvent does not include the the `errors` kwarg: https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L658

**Comment by simskij** [comment]
Libcheck will always fail on PRs from forks, as they don't have access to the secrets. We should probably make it conditional on the remote branch being local to the repo.

**Pull request merged**
